[package]
name = "drive-remote"
version = "0.1.0"
authors = ["David <david.bauske@googlemail.com>"]

[dependencies]
termion = "1.5.1"
nix = "0.10.0"
byteorder = "1.2.1"
serde = "1.0.29"
bincode = "1.0.0"
clap = "2.31.1"
joy = "0.1.3"

messages = { path = "../messages" }